use crate::endpoints::orders::schema::address::{
    Address, PersonFullName, PhoneNumber, PhoneWithType,
};
use crate::endpoints::orders::schema::amount::Amount;
use crate::endpoints::orders::schema::source::VaultStoreInValue;
use crate::endpoints::orders::schema::source::card::{CardNetwork, CardStoredCredential, CardType};
use serde::{Deserialize, Serialize};
use typed_builder::TypedBuilder;

#[serde_with::skip_serializing_none]
#[derive(Debug, Clone, Serialize, Deserialize, TypedBuilder)]
pub struct ApplePaySource {
    /// ApplePay transaction identifier, this will be the unique identifier for this transaction provided by Apple.
    /// The pattern is defined by an external party and supports Unicode.
    #[builder(default, setter(strip_option, into))]
    pub id: Option<String>,

    /// The two-character ISO 3166-1 country code.
    #[builder(setter(into))]
    pub country_code: String,

    /// Provides additional details to process a payment using a card that has been stored or is intended to be stored (also referred to as stored_credential or card-on-file).
    #[builder(default, setter(strip_option, into))]
    pub stored_credential: Option<CardStoredCredential>,

    /// Additional attributes associated with apple pay.
    #[builder(default, setter(strip_option, into))]
    pub attributes: Option<ApplePayAttributes>,

    /// Name on the account holder associated with apple pay.
    #[builder(default, setter(strip_option, into))]
    pub name: Option<String>,

    /// The email address of the account holder associated with apple pay.
    #[builder(default, setter(strip_option, into))]
    pub email_address: Option<String>,

    /// The phone number, in its canonical international E.164 numbering plan format.
    /// Supports only the national_number property.
    #[builder(default, setter(strip_option, into))]
    pub phone_number: Option<PhoneNumber>,

    /// The decrypted payload details for the apple pay token.
    #[builder(default, setter(strip_option, into))]
    pub decrypted_token: Option<ApplePayDecryptedToken>,

    /// The PayPal-generated ID for the saved apple pay payment_source.
    /// This ID should be stored on the merchant's server so the saved payment source can be used for future transactions.
    #[builder(default, setter(strip_option, into))]
    pub vault_id: Option<String>,

    /// Customizes the payer experience during the approval process for the payment.
    #[builder(default, setter(strip_option, into))]
    pub experience_context: Option<ApplePayExperienceContext>,
}

#[serde_with::skip_serializing_none]
#[derive(Debug, Clone, Serialize, Deserialize, TypedBuilder)]
pub struct ApplePayAttributes {
    /// This object represents a merchant’s customer, allowing them to store contact details, and track all payments associated with the same customer.
    #[builder(default, setter(strip_option, into))]
    pub customer: Option<ApplePayCustomer>,

    /// This object represents a merchant’s customer, allowing them to store contact details, and track all payments associated with the same customer.
    #[builder(default, setter(strip_option, into))]
    pub vault: Option<ApplePayVault>,
}

#[serde_with::skip_serializing_none]
#[derive(Debug, Clone, Serialize, Deserialize, TypedBuilder)]
pub struct ApplePayCustomer {
    /// The unique ID for a customer generated by PayPal.
    #[builder(default, setter(strip_option, into))]
    pub id: Option<String>,

    /// Email address of the customer as provided to the merchant or on file with the merchant.
    /// Email Address is required if you are processing the transaction using PayPal Guest Processing which is offered to select partners and merchants.
    #[builder(default, setter(strip_option, into))]
    pub email_address: Option<String>,

    /// The phone number of the customer as provided to the merchant or on file with the merchant. The phone.phone_number supports only national_number.
    #[builder(default, setter(strip_option, into))]
    pub phone: Option<PhoneWithType>,

    /// The full name of the customer as provided to the merchant or on file with the merchant.
    #[builder(default, setter(strip_option, into))]
    pub name: Option<PersonFullName>,
}

#[serde_with::skip_serializing_none]
#[derive(Debug, Clone, Serialize, Deserialize, TypedBuilder)]
pub struct ApplePayVault {
    /// Defines how and when the payment source gets vaulted.
    #[builder(setter(into))]
    pub store_in_value: VaultStoreInValue,
}

#[serde_with::skip_serializing_none]
#[derive(Debug, Clone, Serialize, Deserialize, TypedBuilder)]
pub struct ApplePayExperienceContext {
    /// The URL where the customer is redirected after the customer approves the payment.
    #[builder(setter(into))]
    pub return_url: String,

    /// The URL where the customer is redirected after the customer cancels the payment.
    #[builder(setter(into))]
    pub cancel_url: String,
}

#[derive(Debug, Serialize, Deserialize, Eq, PartialEq, Clone, Copy)]
#[allow(missing_docs)]
pub enum ApplePaymentDataType {
    /// The card was authenticated using 3D Secure (3DS) authentication scheme.
    /// While using this value make sure to populate cryptogram and eci_indicator as part of payment data..
    #[serde(rename = "3DSECURE")]
    ThreeDSecure,
    #[serde(rename = "EMV")]
    Emv,
}

#[serde_with::skip_serializing_none]
#[derive(Debug, Clone, Serialize, Deserialize, TypedBuilder)]
pub struct ApplePayDecryptedToken {
    /// Apple Pay Hex-encoded device manufacturer identifier.
    /// The pattern is defined by an external party and supports Unicode.
    #[builder(default, setter(strip_option, into))]
    pub device_manufacturer_id: Option<String>,

    /// Indicates the type of payment data passed, in case of Non China the payment data is 3DSECURE and for China it is EMV.
    #[builder(default, setter(strip_option, into))]
    pub payment_data_type: Option<ApplePaymentDataType>,

    /// The transaction amount for the payment that the payer has approved on apple platform.
    #[builder(default, setter(strip_option, into))]
    pub transaction_amount: Option<Amount>,

    /// Apple Pay tokenized credit card used to pay.
    #[builder(setter(into))]
    pub tokenized_card: ApplePayTokenizedCard,

    /// Apple Pay payment data object which contains the cryptogram, eci_indicator and other data.
    #[builder(default, setter(strip_option, into))]
    pub payment_data: Option<ApplePayPaymentData>,
}

#[serde_with::skip_serializing_none]
#[derive(Debug, Clone, Serialize, Deserialize, TypedBuilder)]
pub struct ApplePayTokenizedCard {
    /// The card holder's name as it appears on the card.
    #[builder(default, setter(strip_option, into))]
    pub name: Option<String>,

    /// The primary account number (PAN) for the payment card.
    #[builder(default, setter(strip_option, into))]
    pub number: Option<String>,

    /// The card expiration year and month, in Internet date format For example: 2028-04
    #[builder(default, setter(strip_option, into))]
    pub expiry: Option<String>,

    /// The payment card type.
    #[serde(rename = "type")]
    #[builder(default, setter(strip_option, into))]
    pub card_type: Option<CardType>,

    /// The card brand or network. Typically used in the response.
    #[builder(default, setter(strip_option, into))]
    pub brand: Option<CardNetwork>,

    /// The billing address for this card.
    /// Supports only the address_line_1, address_line_2, admin_area_1, admin_area_2, postal_code, and country_code properties.
    #[builder(default, setter(strip_option, into))]
    pub billing_address: Option<Address>,
}

#[serde_with::skip_serializing_none]
#[derive(Debug, Clone, Serialize, Deserialize, TypedBuilder)]
pub struct ApplePayPaymentData {
    /// Online payment cryptogram, as defined by 3D Secure.
    /// The pattern is defined by an external party and supports Unicode.
    #[builder(default, setter(strip_option, into))]
    pub cryptogram: Option<String>,

    /// ECI indicator, as defined by 3- Secure.
    /// The pattern is defined by an external party and supports Unicode.
    #[builder(default, setter(strip_option, into))]
    pub eci_indicator: Option<String>,

    /// Encoded Apple Pay EMV Payment Structure used for payments in China.
    /// The pattern is defined by an external party and supports Unicode.
    #[builder(default, setter(strip_option, into))]
    pub emv_data: Option<String>,

    /// Bank Key encrypted Apple Pay PIN.
    /// The pattern is defined by an external party and supports Unicode.
    #[builder(default, setter(strip_option, into))]
    pub pin: Option<String>,
}
