use crate::endpoints::orders::schema::address::{Address, PersonFullName, PhoneWithType};
use crate::endpoints::orders::schema::source::token::PaymentUsage;
use crate::endpoints::orders::schema::source::{PaymentInitiator, PaymentType, VaultStoreInValue};
use serde::{Deserialize, Serialize};
use typed_builder::TypedBuilder;

#[serde_with::skip_serializing_none]
#[derive(Debug, Clone, Serialize, Deserialize, TypedBuilder)]
pub struct CardSource {
    /// The card holder's name as it appears on the card.
    #[builder(default, setter(strip_option, into))]
    pub name: Option<String>,

    /// The primary account number (PAN) for the payment card.
    #[builder(default, setter(strip_option, into))]
    pub number: Option<String>,

    /// The three- or four-digit security code of the card.
    /// Also known as the CVV, CVC, CVN, CVE, or CID.
    /// This parameter cannot be present in the request when payment_initiator=MERCHANT.
    #[builder(default, setter(strip_option, into))]
    pub security_code: Option<String>,

    /// The card expiration year and month,
    /// in Internet date format For example: 2028-04
    #[builder(default, setter(strip_option, into))]
    pub expiry: Option<String>,

    /// The billing address for this card.
    /// Supports only the address_line_1, address_line_2, admin_area_1, admin_area_2, postal_code, and country_code properties.
    #[builder(default, setter(strip_option, into))]
    pub billing_address: Option<Address>,

    // Additional attributes associated with the use of this card.
    #[builder(default, setter(strip_option, into))]
    pub attributes: Option<CardAttributes>,

    /// Provides additional details to process a payment using a card that has been stored or is intended to be stored (also referred to as stored_credential or card-on-file).
    #[builder(default, setter(strip_option, into))]
    pub stored_credential: Option<CardStoredCredential>,

    /// The PayPal-generated ID for the saved card payment source.
    /// Typically stored on the merchant's server.
    #[builder(default, setter(strip_option, into))]
    pub vault_id: Option<String>,

    /// The PayPal-generated, short-lived, one-time-use token,
    /// used to communicate payment information to PayPal for transaction processing.
    #[builder(default, setter(strip_option, into))]
    pub single_use_token: Option<String>,

    /// A 3rd party network token refers to a network token that the merchant provisions from and vaults with an external TSP (Token Service Provider) other than PayPal.
    #[builder(default, setter(strip_option, into))]
    pub network_token: Option<CardNetworkToken>,

    /// Customizes the payer experience during the 3DS Approval for payment.
    #[builder(default, setter(strip_option, into))]
    pub experience_context: Option<CardExperienceContext>,
}

#[serde_with::skip_serializing_none]
#[derive(Debug, Clone, Serialize, Deserialize, TypedBuilder)]
pub struct CardAttributes {
    /// The details about a customer in PayPal's system of record.
    #[builder(default, setter(strip_option, into))]
    pub customer: Option<CardCustomer>,

    /// Instruction to vault the card based on the specified strategy.
    #[builder(default, setter(strip_option, into))]
    pub vault: Option<CardVault>,

    /// Instruction to optionally verify the card based on the specified strategy.
    #[builder(default, setter(strip_option, into))]
    pub verification: Option<CardVerification>,
}

#[serde_with::skip_serializing_none]
#[derive(Debug, Clone, Serialize, Deserialize, TypedBuilder)]
pub struct CardCustomer {
    /// The unique ID for a customer generated by PayPal.
    #[builder(default, setter(strip_option, into))]
    pub id: Option<String>,

    /// Email address of the customer as provided to the merchant or on file with the merchant.
    /// Email Address is required if you are processing the transaction using PayPal Guest Processing which is offered to select partners and merchants.
    #[builder(default, setter(strip_option, into))]
    pub email_address: Option<String>,

    /// The phone number of the customer as provided to the merchant or on file with the merchant.
    /// The phone.phone_number supports only national_number.
    #[builder(default, setter(strip_option, into))]
    pub phone: Option<PhoneWithType>,

    /// The full name of the customer as provided to the merchant or on file with the merchant.
    #[builder(default, setter(strip_option, into))]
    pub name: Option<PersonFullName>,

    /// Merchants and partners may already have a data-store where their customer information is persisted.
    /// Use merchant_customer_id to associate the PayPal-generated customer.id to your representation of a customer.
    #[builder(default, setter(strip_option, into))]
    pub merchant_customer_id: Option<String>,
}

#[serde_with::skip_serializing_none]
#[derive(Debug, Clone, Serialize, Deserialize, TypedBuilder)]
pub struct CardVault {
    /// Defines how and when the payment source gets vaulted.
    #[builder(default, setter(strip_option, into))]
    pub store_in_vault: Option<VaultStoreInValue>,
}

#[derive(Debug, Serialize, Deserialize, Eq, PartialEq, Clone, Copy)]
#[allow(missing_docs)]
pub enum CardVerificationMethod {
    #[serde(rename = "SCA_ALWAYS")]
    ScaAlways,
    #[serde(rename = "SCA_WHEN_REQUIRED")]
    ScaWhenRequired,
    #[serde(rename = "3D_SECURE")]
    ThreeDSecure,
    #[serde(rename = "AVS_CVV")]
    AvsCvv,
}

#[serde_with::skip_serializing_none]
#[derive(Debug, Clone, Serialize, Deserialize, TypedBuilder)]
pub struct CardVerification {
    /// Defines how and when the payment source gets vaulted.
    #[builder(default, setter(strip_option, into))]
    pub method: Option<CardVerificationMethod>,
}

#[serde_with::skip_serializing_none]
#[derive(Debug, Clone, Serialize, Deserialize, TypedBuilder)]
pub struct CardStoredCredential {
    /// The person or party who initiated or triggered the payment.
    #[builder(setter(into))]
    pub payment_initiator: PaymentInitiator,

    /// Indicates the type of the stored payment_source payment.
    #[builder(setter(into))]
    pub payment_type: PaymentType,

    /// The person or party who initiated or triggered the payment.
    #[builder(default, setter(into))]
    pub usage: PaymentUsage,

    /// Reference values used by the card network to identify a transaction.
    #[builder(default, setter(strip_option, into))]
    pub previous_network_transaction_reference: Option<CardPreviousTransactionReference>,
}

#[derive(Debug, Serialize, Deserialize, Eq, PartialEq, Clone, Copy)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
#[allow(missing_docs)]
pub enum CardType {
    /// A credit card.
    Credit,
    /// A debit card.
    Debit,
    /// A Prepaid card.
    Prepaid,
    /// A store card.
    Store,
    /// Card type cannot be determined.
    Unknown,
}

#[derive(Debug, Serialize, Deserialize, Eq, PartialEq, Clone, Copy)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
#[allow(missing_docs)]
pub enum CardNetwork {
    /// Visa card.
    Visa,
    /// Mastercard card.
    Mastercard,
    /// Discover card.
    Discover,
    /// American Express card.
    Amex,
    /// Solo debit card.
    Solo,
    /// Japan Credit Bureau card.
    Jcb,
    /// Military Star card.
    Star,
    /// Delta Airlines card.
    Delta,
    /// Switch credit card.
    Switch,
    /// Maestro credit card.
    Maestro,
    /// Carte Bancaire (CB) credit card.
    CbNationale,
    /// Configoga credit card.
    Configoga,
    /// Confidis credit card.
    Confidis,
    /// Visa Electron credit card.
    Electron,
    /// Cetelem credit card.
    Cetelem,
    /// China union pay credit card.
    ChinaUnionPay,
    /// The Diners Club International banking and payment services capability network owned by Discover Financial Services (DFS),
    /// one of the most recognized brands in US financial services.
    Diners,
    /// The Brazilian Elo card payment network.
    Elo,
    /// The Hiper - Ingenico ePayment network.
    Hiper,
    /// The Brazilian Hipercard payment network that's widely accepted in the retail market.
    Hipercard,
    /// The RuPay payment network.
    Rupay,
    /// The GE Credit Union 3Point card payment network.
    Ge,
    /// The Synchrony Financial (SYF) payment network.
    Synchrony,
    /// The Electronic Fund Transfer At Point of Sale(EFTPOS) Debit card payment network.
    Eftpos,
    /// The Carte Bancaire payment network.
    CarteBancaire,
    /// The Star Access payment network.
    StarAccess,
    /// The Pulse payment network.
    Pulse,
    /// The NYCE payment network.
    Nyce,
    /// The Accel payment network.
    Accel,
    /// UNKNOWN payment network.
    Unknown,
}

#[serde_with::skip_serializing_none]
#[derive(Debug, Clone, Serialize, Deserialize, TypedBuilder)]
pub struct CardPreviousTransactionReference {
    /// Transaction reference id returned by the scheme. For Visa and Amex, this is the "Tran id" field in response.
    /// For MasterCard, this is the "BankNet reference id" field in response.
    /// For Discover, this is the "NRID" field in response.
    /// The pattern we expect for this field from Visa/Amex/CB/Discover is numeric, Mastercard/BNPP is alphanumeric and Paysecure is alphanumeric with special character -.
    #[builder(default, setter(strip_option, into))]
    pub id: Option<String>,

    /// The date that the transaction was authorized by the scheme.
    /// This field may not be returned for all networks.
    /// MasterCard refers to this field as "BankNet reference date.
    #[builder(default, setter(strip_option, into))]
    pub date: Option<String>,

    /// Reference ID issued for the card transaction.
    /// This ID can be used to track the transaction across processors, card brands and issuing banks.
    #[builder(default, setter(strip_option, into))]
    pub acquirer_reference_number: Option<String>,

    /// Name of the card network through which the transaction was routed.
    #[builder(default, setter(strip_option, into))]
    pub network: Option<CardNetwork>,
}

#[derive(Debug, Serialize, Deserialize, Eq, PartialEq, Clone, Copy)]
#[allow(clippy::enum_variant_names)]
pub enum CardEciFlag {
    /// Mastercard non-3-D Secure transaction.
    #[serde(rename = "MASTERCARD_NON_3D_SECURE_TRANSACTION")]
    MastercardNon3dSecureTransaction,

    /// Mastercard attempted authentication transaction.
    #[serde(rename = "MASTERCARD_ATTEMPTED_AUTHENTICATION_TRANSACTION")]
    MastercardAttemptedAuthenticationTransaction,

    /// Mastercard fully authenticated transaction.
    #[serde(rename = "MASTERCARD_FULLY_AUTHENTICATED_TRANSACTION")]
    MastercardFullyAuthenticatedTransaction,

    /// VISA, AMEX, JCB, DINERS CLUB fully authenticated transaction.
    #[serde(rename = "FULLY_AUTHENTICATED_TRANSACTION")]
    FullyAuthenticatedTransaction,

    /// VISA, AMEX, JCB, DINERS CLUB attempted authentication transaction.
    #[serde(rename = "ATTEMPTED_AUTHENTICATION_TRANSACTION")]
    AttemptedAuthenticationTransaction,

    /// VISA, AMEX, JCB, DINERS CLUB non-3-D Secure transaction.
    #[serde(rename = "NON_3D_SECURE_TRANSACTION")]
    Non3dSecureTransaction,
}

#[serde_with::skip_serializing_none]
#[derive(Debug, Clone, Serialize, Deserialize, TypedBuilder)]
pub struct CardNetworkToken {
    /// Third party network token number.
    #[builder(default, setter(strip_option, into))]
    pub token: Option<String>,

    /// An Encrypted one-time use value that's sent along with Network Token.
    /// This field is not required to be present for recurring transactions.
    #[builder(default, setter(strip_option, into))]
    pub cryptogram: Option<String>,

    /// A TRID, or a Token Requestor ID, is an identifier used by merchants to request network tokens from card networks.
    /// A TRID is a precursor to obtaining a network token for a credit card primary account number (PAN), and will aid in enabling secure card on file (COF) payments and reducing fraud.
    #[builder(default, setter(strip_option, into))]
    pub token_requestor_id: Option<String>,

    /// The card expiration year and month, in Internet date format.
    #[builder(default, setter(into))]
    pub expiry: String,

    /// Electronic Commerce Indicator (ECI).
    /// The ECI value is part of the 2 data elements that indicate the transaction was processed electronically.
    /// This should be passed on the authorization transaction to the Gateway/Processor.
    #[builder(default, setter(strip_option, into))]
    pub eci_flag: Option<CardEciFlag>,
}

#[serde_with::skip_serializing_none]
#[derive(Debug, Clone, Serialize, Deserialize, TypedBuilder)]
pub struct CardExperienceContext {
    /// The URL where the customer will be redirected upon successfully completing the 3DS challenge.
    #[builder(default, setter(strip_option, into))]
    pub return_url: Option<String>,

    /// The URL where the customer will be redirected upon cancelling the 3DS challenge.
    #[builder(default, setter(strip_option, into))]
    pub cancel_url: Option<String>,
}
