use crate::endpoints::orders::schema::address::{PersonFullName, PhoneWithType};
use crate::endpoints::orders::schema::source::{ShippingPreference, VaultStoreInValue};
use serde::{Deserialize, Serialize};
use typed_builder::TypedBuilder;

#[serde_with::skip_serializing_none]
#[derive(Debug, Clone, Serialize, Deserialize, TypedBuilder)]
pub struct VenmoSource {
    /// Customizes the buyer experience during the approval process for payment with Venmo.
    #[builder(default, setter(strip_option, into))]
    pub experience_context: Option<VenmoExperienceContext>,

    /// The PayPal-generated ID for the saved Venmo wallet payment_source.
    /// This ID should be stored on the merchant's server so the saved payment source can be used for future transactions.
    #[builder(default, setter(strip_option, into))]
    pub vault_id: Option<String>,

    /// The email address of the payer.
    #[builder(default, setter(strip_option, into))]
    pub email_address: Option<String>,

    /// Additional attributes associated with the use of this wallet.
    #[builder(default, setter(strip_option, into))]
    pub attributes: Option<VenmoAttributes>,
}

#[serde_with::skip_serializing_none]
#[derive(Debug, Clone, Serialize, Deserialize, TypedBuilder)]
pub struct VenmoOrderUpdateCallbackConfig {
    /// An array of callback events merchant can subscribe to for the corresponding callback url.
    #[builder(setter(into))]
    pub callback_events: Vec<String>,

    /// Merchant provided CallBack url.PayPal/Venmo will use this url to call the merchant back when the events occur .
    /// PayPal/Venmo expects a secured url usually in the https format.merchant can append the cart id or other params part of the url as query or path params.
    #[builder(setter(into))]
    pub callback_url: String,
}

#[serde_with::skip_serializing_none]
#[derive(Debug, Clone, Serialize, Deserialize, TypedBuilder)]
pub struct VenmoExperienceContext {
    /// The label that overrides the business name in the PayPal account on the PayPal site. The pattern is defined by an external party and supports Unicode.
    #[builder(default, setter(strip_option, into))]
    pub brand_name: Option<String>,

    /// The location from which the shipping address is derived.
    #[builder(default, setter(into))]
    pub shipping_preference: ShippingPreference,

    /// Merchant provided Order Update callback configuration for PayPal Wallet.PayPal will call back merchant when the specified event occurs.
    /// we recommend merchants to pass both the shipping_options and shipping_address callback events.
    /// Not supported when shipping.type is specified or when 'application_context.shipping_preference' is set as 'NO_SHIPPING' or 'SET_PROVIDED_ADDRESS'.
    #[builder(default, setter(strip_option, into))]
    pub order_update_callback_config: Option<VenmoOrderUpdateCallbackConfig>,
}

#[serde_with::skip_serializing_none]
#[derive(Debug, Clone, Serialize, Deserialize, TypedBuilder)]
pub struct VenmoAttributes {
    /// This object represents a merchant’s customer, allowing them to store contact details,
    /// and track all payments associated with the same customer.
    #[builder(default, setter(strip_option, into))]
    pub customer: Option<VenmoCustomer>,

    /// Attributes used to provide the instructions during vaulting of the Venmo Wallet.
    #[builder(default, setter(strip_option, into))]
    pub vault: Option<VenmoVault>,
}

#[derive(Debug, Clone, Serialize, Deserialize, TypedBuilder)]
pub struct VenmoCustomer {
    /// The unique ID for a customer generated by PayPal.
    #[builder(default, setter(strip_option, into))]
    pub id: Option<String>,

    /// Email address of the customer as provided to the merchant or on file with the merchant.
    /// Email Address is required if you are processing the transaction using PayPal Guest Processing which is offered to select partners and merchants.
    #[builder(default, setter(strip_option, into))]
    pub email_address: Option<String>,

    /// The phone number of the customer as provided to the merchant or on file with the merchant.
    /// The phone.phone_number supports only national_number.
    #[builder(default, setter(strip_option, into))]
    pub phone: Option<PhoneWithType>,

    /// The full name of the customer as provided to the merchant or on file with the merchant.
    #[builder(default, setter(strip_option, into))]
    pub name: Option<PersonFullName>,
}

#[serde_with::skip_serializing_none]
#[derive(Debug, Clone, Serialize, Deserialize, TypedBuilder)]
pub struct VenmoVault {
    /// Defines how and when the payment source gets vaulted.
    #[builder(default, setter(strip_option, into))]
    pub store_in_vault: Option<VaultStoreInValue>,

    /// The description displayed to Venmo consumer on the approval flow for Venmo,
    /// as well as on the Venmo payment token management experience on Venmo.com.
    #[builder(default, setter(strip_option, into))]
    pub description: Option<String>,

    /// Expected business/pricing model for the billing agreement.
    #[builder(default, setter(strip_option, into))]
    pub usage_pattern: Option<String>,

    /// The usage type associated with the Venmo payment token.
    #[builder(setter(into))]
    pub usage_type: String,

    /// The customer type associated with the Venmo payment token.
    /// This is to indicate whether the customer acting on the merchant / platform is either a business or a consumer.
    #[builder(default, setter(strip_option, into))]
    pub customer_type: Option<String>,

    /// Create multiple payment tokens for the same payer, merchant/platform combination.
    /// Use this when the customer has not logged in at merchant/platform.
    /// The payment token thus generated, can then also be used to create the customer account at merchant/platform.
    /// Use this also when multiple payment tokens are required for the same payer, different customer at merchant/platform. This helps to identify customers distinctly even though they may share the same Venmo account.
    #[builder(setter(strip_bool))]
    pub permit_multiple_payment_tokens: bool,
}
